Feat/button component v2
nightborn-be/localise-frontend pull request #1
Opened 2023-02-16 09:41 UTC by youssef-night

2023-02-16 13:22 UTC, m-Nightly requested changes

2023-02-16 13:22 UTC, m-Nightly commented on libs/ui/components/inputs/button/index.tsx
> +    h,
Not being uised? I would use the Chakra Props and spread

2023-02-16 13:22 UTC, m-Nightly commented
Good job !

2023-02-16 13:54 UTC, youssef-night commented on libs/ui/components/inputs/button/index.tsx
> +    h,
This pull request is only for ButtonIcon, so this other component will be make later

2023-02-21 10:11 UTC, m-Nightly approved these changes
LGTM !

2023-02-21 10:20 UTC, merged