Navigation component
nightborn-be/localise-frontend pull request #10
Opened 2023-03-09 16:00 UTC by youssef-night

2023-03-13 08:06 UTC, ThomasNight requested changes

2023-03-13 08:06 UTC, ThomasNight commented on libs/ui/components/navigation/breadcrumb/props.ts
> +export interface BreadcrumbElement {
with interfaces add `I` prefix
```suggestion
export interface IBreadcrumbElement {
```

2023-03-13 08:06 UTC, ThomasNight commented on libs/ui/components/navigation/tabs/tab/index.tsx
>          <Text
use Paragraph
and Box or Flex for parent to have onClick props

2023-03-14 07:22 UTC, ThomasNight requested changes

2023-03-14 07:22 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/index.stories.tsx
> +            stroke={{ isHovered } ? '#F46363' : '#8F95B2'}
```suggestion
            stroke={ isHovered  ? '#F46363' : '#8F95B2'}
```
I don't know why you put it in an object

2023-03-14 07:22 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/index.stories.tsx
> +            stroke={{ isHovered } ? '#F46363' : '#8F95B2'}
same here

2023-03-14 07:22 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/props.ts
>  export enum ButtonSize {
move it to types.ts

2023-03-14 07:22 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/types.ts
> +type State = {
To generic
E.g. ButtonIconState

2023-03-14 07:22 UTC, ThomasNight commented on libs/ui/components/navigation/breadcrumb/props.ts
> +export interface BreadcrumbElement {
Todo

2023-03-14 07:22 UTC, ThomasNight commented on libs/ui/components/navigation/breadcrumb/props.ts
> +export interface BreadcrumbElement {
And move it to types.ts

2023-03-14 07:22 UTC, ThomasNight commented on libs/ui/components/navigation/tabs/tab/index.tsx
>  const Tab = ({ children, onSelect, active }: ITabProps): JSX.Element => {
```suggestion
const Tab = ({ children, onSelect, isActive }: ITabProps): JSX.Element => {
```

2023-03-14 10:36 UTC, youssef-night commented on libs/ui/components/inputs/button-icon/index.stories.tsx
> +            stroke={{ isHovered } ? '#F46363' : '#8F95B2'}
I just forgot to change it after a "replace all"

2023-03-15 19:01 UTC, ThomasNight approved these changes

2023-03-15 19:01 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/types.ts
> +    XS = "1.75rem", SMALL = "2rem", REGULAR = "2.25rem", LARGE = "2.5rem", XL = "2.75rem", XXL = "3rem"
Enum should not be used to set values
XS = "XS"

and in the component if (size == XS) return "1.75rem"

2023-03-16 09:27 UTC, merged