Content component
nightborn-be/localise-frontend pull request #12
Opened 2023-03-10 15:52 UTC by youssef-night

2023-03-14 07:58 UTC, ThomasNight requested changes

2023-03-14 07:58 UTC, ThomasNight commented on libs/ui/.storybook/preview.js
> +});
don't use next image, use react image instead

2023-03-14 07:58 UTC, ThomasNight commented on libs/ui/components/contents/avatar/index.tsx
> +export default function Avatar({ text, imageSrc }: ITooltipProps) {
```suggestion
export default function Avatar({ name, imageSrc }: ITooltipProps) {
```

2023-03-14 07:58 UTC, ThomasNight commented on libs/ui/components/contents/role/index.tsx
> +export default function Role({ text, color, backgroundColor }: IRoleProps) {
It's a tag but with a different shape and color

2023-03-14 07:58 UTC, ThomasNight commented on libs/ui/components/contents/tooltip/props.ts
> +export default interface ITooltipProps extends TooltipProps {
```suggestion
export interface ITooltipProps extends TooltipProps {
```

Use default for component but not for props

2023-03-14 07:58 UTC, ThomasNight commented on libs/ui/components/contents/tooltip/index.tsx
> +    ...props
for now there is two types of tooltips add a kind props instead DEFAULT or COMMAND

2023-03-14 07:58 UTC, ThomasNight commented on libs/ui/components/contents/tooltip/index.tsx
> +    ...props
And label should not get an array, it should be a string
And you can add another param if you want to show the command icon

2023-03-14 09:28 UTC, youssef-night commented on libs/ui/.storybook/preview.js
> +});
I use Image from Chakra it's good ?

2023-03-14 09:30 UTC, youssef-night commented on libs/ui/components/contents/role/index.tsx
> +export default function Role({ text, color, backgroundColor }: IRoleProps) {
So I delete that component and make it in the tag ? because in tag component I have some animation I need to do a specific condition when it's a role tag ? or I keep that

2023-03-14 09:31 UTC, youssef-night commented on libs/ui/components/contents/tooltip/index.tsx
> +    ...props
I delete the array from stories and create a enum TooltipType { DEFAULT,COMMAND}, I have also command props 
if it's COMMAND then i use label like a array it's good ?

2023-03-15 19:03 UTC, ThomasNight approved these changes

2023-03-16 09:22 UTC, merged