Feat/default and login page
nightborn-be/localise-frontend pull request #14
Opened 2023-03-24 12:01 UTC by youssef-night

2023-03-27 10:45 UTC, ThomasNight requested changes

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/components/contents/page/index.tsx
> +        <HStack justify={'center'} w='100%' h='100vh'>
```suggestion
        <HStack justify='center' w='full' h='screen'>
```
full = 100%
screen = 100vh

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/components/contents/page/index.tsx
> +                justifyContent={'center'}
```suggestion
                alignItems='start'
                bgImage={bgImage}
                bgSize='cover'
                justifyContent='center'
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/index.tsx
> +    const { handleLogInRedirecton, handleSignInRedirection } = useAuthLogic();
```suggestion
    const { handleLogInRedirecton, handleSignInRedirection } = useAuthHomeLogic();
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/index.tsx
> +                        {t(tKeys.home.welcom.title)}
```suggestion
                        {t(tKeys.auth.home.title)}
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/index.tsx
> +                        {t(tKeys.common.buttonLogin) ?? ''}
```suggestion
                        {t(tKeys.auth.home.cta.sign_in)}
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/index.tsx
> +                        {t(tKeys.home.buttonSignup) ?? ''}
```suggestion
                        {t(tKeys.auth.home.cta.sign_up)}
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/logic.ts
> +        return;
return not needed

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/logic.ts
> +export const useAuthLogic = (): AuthLogicType => {
```suggestion
export const useAuthHomeLogic = (): AuthHomeLogicResponse => {
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/index.tsx
> +export default function LoginPage() {
```suggestion
export default function SignInPage() {
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/index.tsx
> +    const { handleOnSubmit, form } = useLoginLogic();
```suggestion
    const { handleOnSubmit, form } = useSignInLogic();
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/index.tsx
> +                    {t(tKeys.login.title)}
```suggestion
                    {t(tKeys.auth.sign_in.title)}
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/index.tsx
> +                        label={t(tKeys.login.inputLabel.email)}
```suggestion
                        label={t(tKeys.auth.sign_in.form.email.title)}
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/index.tsx
> +                        isValid={form.email.meta?.error === undefined}
```suggestion
                        isValid={!form.email.meta?.error}
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/index.tsx
> +                        isValid={form.password.meta?.error === undefined}
same

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/logic.ts
> +    const form = createForm(values, rest);
But you don't need it for now right ?

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/types.ts
> +    handleOnSubmit(): void;
```suggestion
    handleOnSubmit: () => void;
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/login/validations.ts
> +    password: Yup.string().required('Password is required'),
add translations
for `email()` too

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/types.ts
> +    handleSignInRedirection(): void;
```suggestion
    handleSignInRedirection: () => void;
```

2023-03-27 10:45 UTC, ThomasNight commented on libs/ui/pages/auth/types.ts
> +    handleLogInRedirecton(): void;
```suggestion
    handleLogInRedirecton: () => void;
```

2023-03-28 13:03 UTC, ThomasNight commented on libs/ui/pages/auth/login/logic.ts
> +        auth?.signIn(values.email, values.password)
you should wait the sign in method to be finished before checking if the user is logged in (because this is an async method)

sign in method should send you an error if it fails

```ts
try {
    await auth.signIn(...)
} catch (err) {
    toast.show(...)
}
```

2023-03-28 13:16 UTC, ThomasNight commented on libs/utils/storage-keys.ts
> +    EMAIL: 'Email'
```suggestion
    EMAIL: 'Email'
```

Not sure why you need it

2023-03-28 13:20 UTC, ThomasNight commented on libs/utils/token.ts
> +    ID_TOKEN = 'id_token',
```suggestion
    ID_TOKEN = StorageKey.ID_TOKEN,
```

2023-03-28 13:21 UTC, ThomasNight commented on libs/utils/token.ts
> +        console.error('Error when storing tokens :', err)
throw error, will be handled by the code who calls this method
if we should console.log or show a toast, etc...
same thing for the other methods

2023-03-29 10:32 UTC, ThomasNight requested changes

2023-03-29 10:32 UTC, ThomasNight commented on libs/ui/auth/context.ts
> +    firebaseUser?: UserCredential.User;
Don't return the firebase user, because we don't want the application to be linked to one provider, imagine if you don't use firebase anymore but you are using another iam for example azure, you will need to change your application where you use firebaseUser and not only the useAuth hook

2023-03-29 10:32 UTC, ThomasNight commented on libs/ui/auth/logic.ts
> +                id_token: token,
Use enum

2023-03-29 10:32 UTC, ThomasNight commented on libs/ui/auth/logic.ts
> +        setApp(initializeApp(firebaseConfig));
I don't think you need to store the app

2023-03-29 10:32 UTC, ThomasNight commented on libs/ui/auth/logic.ts
> +        setAuth(getAuth());
Don't store it, you can use getAuth when you need it

2023-03-29 10:32 UTC, ThomasNight commented on libs/ui/pages/auth/login/logic.ts
> +            await auth?.signIn(values.email, values.password);
auth? => auth 
Auth will never be undefined

2023-03-29 10:32 UTC, ThomasNight commented on libs/utils/token/token.ts
> +    try {
Don't use try catch if you throw directly the error

2023-03-29 10:32 UTC, ThomasNight commented on libs/utils/token/token.ts
> +    try {
Same

2023-03-29 10:32 UTC, ThomasNight commented on libs/utils/token/token.ts
> +        return await storage.get(token);
await storage.get(token)

2023-03-29 10:32 UTC, ThomasNight commented on libs/utils/token/token.ts
> +const getTokenFromStorage = async (token: string) => {
Use enum and map it to storage key enum

2023-03-29 10:32 UTC, ThomasNight commented on libs/utils/token/token.ts
> +const removeTokenFromStorage = async (token: string) => {
Same

2023-03-29 10:32 UTC, ThomasNight commented on libs/utils/token/token.ts
> +                return storage.save(key, value);
Map key to storageKey enum

2023-03-29 12:56 UTC, youssef-night commented on libs/ui/auth/logic.ts
> +        setApp(initializeApp(firebaseConfig));
I init the app in a use effect so I can have access to my init outside de useEffect is for that I store the app in a state

2023-03-29 13:47 UTC, closed without merging