Button text component
nightborn-be/localise-frontend pull request #2
Opened 2023-02-21 09:24 UTC by youssef-night

2023-02-21 14:44 UTC, ThomasGnightborn requested changes
I've seen good things and other a little less good but it's normal for a first review ;) 

A first rule that you can keep is mind is never duplicate code (DRY principle) (for example your start/endhancer with deepClone was repeated 4 times (it's 3 times too much).

A second rule that you can keep in mind is try to create more little components it has 2 advantages : 
1. more readability in your code, it's better to have a Component with an explicit name and it's own logic that a 300lines of render with a lot of unordered logic
2. When your component has it's own index.tsx it'll render properly (only if this component change) if you put all your logic into a big render function, all of your component will change even tho it's only a small portion of your code was updated)

Third rule that you can keep in mind (maybe not relevant in this PR but good for later) : 
don't hesitate to comment your code and create utils methods (utils method are little snippets of code that compute/do certain action and can be reused among your all of your code)

Last rule: Don't hesitate to ask question (there is no dumb question only dumb responses)

2023-02-22 11:36 UTC, youssef-night commented on libs/ui/components/inputs/button-icon/index.stories.tsx
> +    hoverBackgroundColor: '#4C36B5',
No directly take the color on figma inspect

2023-02-27 10:07 UTC, ThomasGnightborn requested changes
Just little things to change but otherwise it's good ! Well done @youssef-night  !

2023-02-27 10:07 UTC, ThomasGnightborn commented on libs/ui/components/inputs/button/index.tsx
> +                {startEnhancer && startEnhancer(enhancerProps)}
Better to do : 
`startEnhancer ? startEnhancer(enhancerProps) : null` if your condition before the && is not a boolean 

(Read me about it here : https://medium.com/geekculture/stop-using-for-conditional-rendering-in-react-a0f7b96200f8)

2023-02-27 10:07 UTC, ThomasGnightborn commented on libs/ui/components/inputs/button/index.tsx
> +                {endEnhancer && endEnhancer(enhancerProps)}
Same as the startEnhancer

2023-02-27 10:07 UTC, ThomasGnightborn commented on libs/ui/components/inputs/button/props.ts
> +    isHovered: boolean | undefined;
```suggestion
    isHovered?: boolean;
```

With the ?: it will be undefined if you don't specify it in the props

2023-02-28 10:28 UTC, ThomasGnightborn approved these changes

2023-03-01 10:56 UTC, merged