Feat/routes and redirect
nightborn-be/localise-frontend pull request #28
Opened 2023-04-28 14:40 UTC by youssef-night

2023-05-02 09:11 UTC, ThomasNight commented on apps/front-end/pages/_app.tsx
> +function MyApp({ Component, pageProps, router }: AppProps) {
not needed you can remove it

2023-05-02 09:12 UTC, ThomasNight commented on apps/front-end/pages/dashboard/index.tsx
> +const DashboardWeb = () => {
Add spacing for visibility

2023-05-02 09:13 UTC, ThomasNight commented on apps/front-end/pages/dashboard/index.tsx
> +    useRouter();
// Attributes

2023-05-02 09:13 UTC, ThomasNight commented on apps/front-end/pages/dashboard/index.tsx
> +    return <Dashboard />;
// Render

2023-05-02 09:13 UTC, ThomasNight commented on apps/front-end/pages/dashboard/projects/[id]/index.tsx
> +const ProjectWeb = () => {
Same everywhere

2023-05-02 09:14 UTC, ThomasNight commented on libs/ui/auth/auth-redirect.ts
> +    let currentRoute = route ?? router.asPath;
const

2023-05-02 09:15 UTC, ThomasNight commented on libs/ui/auth/context.ts
> +    setIsLoading: (value: boolean) => void;
Tu ne devrais pas pouvoir modifier le loading en dehors du provider

2023-05-02 09:16 UTC, ThomasNight commented on libs/ui/auth/logic.ts
>          const data = await signInWithEmailAndPassword(auth, email, password);
do a try catch

Because if this fail the setIsLoading(false) will not be executed

2023-05-02 09:19 UTC, ThomasNight commented on libs/ui/components/sidebar/create-project-modal/index.tsx
> +    isDisableOnCloseProjectModal,
```suggestion
    isDisableOnClose, -> You are already on the project modal
```

2023-05-02 09:19 UTC, ThomasNight commented on libs/ui/components/sidebar/create-project-modal/index.tsx
>      isOpen,
Your file should match your component name

2023-05-02 09:20 UTC, ThomasNight commented on libs/ui/components/sidebar/index.tsx
>      const createOrganisationModal = useDisclosure();
```suggestion
    const {onOpen, ...} = useDisclosure();
```

2023-05-02 09:22 UTC, ThomasNight commented on libs/ui/components/sidebar/index.tsx
> +                                                setFilterProjectValue,
Tu ne devrais pas donner ces functions en param
Il devrait déjà être géré dans ton handleOnClickProject

2023-05-02 09:26 UTC, ThomasNight commented on libs/ui/components/sidebar/logic.ts
> +            }
You should not set states when you redirect to another page, you can add query params to know if you need to open a modal or not

2023-05-02 09:27 UTC, ThomasNight commented on libs/ui/pages/auth/index.tsx
> +export default function AuthHomePage({ redirectUrl }: IAuthHomePageProps) {
add spacing

2023-05-02 09:28 UTC, ThomasNight commented on libs/ui/pages/auth/logic.ts
> +            );
Add return -> router.push will not end the function

2023-05-02 09:28 UTC, ThomasNight commented on libs/ui/pages/auth/logic.ts
> +        }
same

2023-05-02 09:29 UTC, ThomasNight commented on libs/ui/pages/auth/sign-in/logic.ts
> +                push('/');
```suggestion
                push('/dashboard');
```

2023-05-02 09:29 UTC, ThomasNight commented on libs/ui/pages/auth/sign-in/logic.ts
> +            auth.setIsLoading(false);
The sign in method will handle that

2023-05-02 09:34 UTC, ThomasNight commented on libs/ui/pages/dashboard/mappers.ts
> +    return res;
```suggestion
    cons source = languages.find(language => language.name === sourceLanguage)
    const targets = targetLanguages.map(language => languages.find(lang => lang.name === language))

    const res: UpdateProjectDTO = {
        name: projectName,
        sourceLanguage: source,
        languages: target,
    };

    return res;
```

2023-05-02 19:35 UTC, ThomasNight requested changes

2023-05-02 19:35 UTC, ThomasNight commented on libs/ui/auth/logic.ts
>          const data = await signInWithEmailAndPassword(auth, email, password);
Why did you remove the isLoading ? you need it for the sign in

2023-05-02 19:35 UTC, ThomasNight commented on libs/ui/pages/auth/logic.ts
> +        return router.push('/auth/sign-up');
```suggestion
        if (redirectUrl) {
            router.push(
                `auth/sign-up?redirectUrl=${encodeURIComponent(redirectUrl)}`,
            );
            return 
        }
        router.push('/auth/sign-up');
```

2023-05-02 19:35 UTC, ThomasNight commented on libs/ui/pages/auth/sign-in/logic.ts
> +    const [isLoading, setIsLoading] = useState<boolean>(false)
isLoading in the auth hook

2023-05-02 19:35 UTC, ThomasNight commented on libs/ui/pages/dashboard/logic.ts
> +        if (projectModalIsOpen == 'true') {
```suggestion
        if (projectModalIsOpen === 'true') {
```

2023-05-02 19:35 UTC, ThomasNight commented on libs/ui/pages/dashboard/logic.ts
> +export const useDashboardLogic = ({ createProjectModalDisclosure } : IDashboardLogicProps) => {
```suggestion
export const useDashboardLogic = ({ onOpenProjectModal } : IDashboardLogicProps) => {
```

2023-05-02 19:35 UTC, ThomasNight commented on libs/ui/pages/dashboard/projects/[id]/logic.ts
> +        ));
remove log

2023-05-02 19:35 UTC, ThomasNight commented on libs/ui/pages/dashboard/props.ts
> +    createProjectModalDisclosure: any
Avoid any

2023-05-02 19:35 UTC, ThomasNight commented on libs/ui/pages/mappers.ts
> +        languages: targets as UpsertProjectLanguageDTO[],
create mapper don't cast

2023-05-03 08:21 UTC, youssef-night commented on libs/ui/pages/auth/sign-in/logic.ts
> +    const [isLoading, setIsLoading] = useState<boolean>(false)
My it's loading is only for make the login statement but I have some problem if I place it in auth hook, without the setIsLoading, in my sign in logic I make a try catch that I use to set error message for my field, from the auth hook I don't have access to him and if I remove the try catch and place it into auth hook I can't use it for set error field message.

2023-05-05 08:59 UTC, ThomasNight approved these changes

2023-05-05 08:59 UTC, ThomasNight commented on libs/ui/auth/logic.ts
> +            setIsLoading(false)
set isLoading false after the token is saved

2023-05-05 08:59 UTC, ThomasNight commented on libs/ui/pages/dashboard/projects/[id]/logic.ts
> +        }
remove

2023-05-05 08:59 UTC, ThomasNight commented on libs/ui/pages/mappers.ts
> +}
```suggestion
const toUpsertProjectLanguageDTO = (object: UpsertProjectLanguageDTO): UpsertProjectLanguageDTO => {
    return object
}
```

Your object shouldn't be empty, if he is you should stop the submit (you don't want to add a term with an empty language)

2023-05-05 08:59 UTC, ThomasNight commented on libs/ui/pages/mappers.ts
> +    return newObject;
```suggestion
  return languages.filter(language => language !== undefined) as UpsertProjectLanguageDTO[]
```

2023-05-05 09:22 UTC, merged