feat: add member for a organisation and fix scroll
nightborn-be/localise-frontend pull request #33
Opened 2023-05-05 15:31 UTC by youssef-night

2023-05-08 09:06 UTC, tahirNight requested changes
some changes to do, the rest seems good to me!

2023-05-08 09:06 UTC, tahirNight commented on libs/ui/components/contents/organisation-settings/props.tsx
> +    members?: UserWithMembershipPagingDTO;
members should'nt be undefined

2023-05-08 09:06 UTC, tahirNight commented on libs/ui/components/sidebar/logic.ts
> +    console.log(members);
remove log

2023-05-08 09:06 UTC, tahirNight commented on libs/ui/components/sidebar/logic.ts
> +    const { data: members } = useGetUsersForOrganisations(actualOrganisationUser?.id as string)
if u cast the id into a string, then no need for the null safety '?'

2023-05-08 09:06 UTC, tahirNight commented on libs/ui/components/sidebar/types.tsx
> +    members?: UserWithMembershipPagingDTO;
members shouldn't be undefined

2023-05-08 10:42 UTC, youssef-night commented on libs/ui/components/sidebar/logic.ts
> +    const { data: members } = useGetUsersForOrganisations(actualOrganisationUser?.id as string)
if you remove the '?' then actualOrganiationUser has an error message as it can be undefined.

2023-05-08 13:48 UTC, tahirNight approved these changes

2023-05-08 15:33 UTC, tahirNight requested changes

2023-05-08 15:33 UTC, tahirNight commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-members/index.tsx
> +                                firstName={member.email as string}
change the prop to email

2023-05-08 15:33 UTC, tahirNight commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-members/index.tsx
> +                            <TableRow
This is not a generic component so name it accordingly and move it to the correct folder

2023-05-08 15:33 UTC, tahirNight commented on libs/ui/components/contents/role/index.tsx
> +        return roleOptions.filter((role) => role.value === selectedValue).at(0);
use find here and not filter

2023-05-08 15:33 UTC, tahirNight commented on libs/ui/components/table/table-row/index.tsx
> +                    }
this will never work as u don't receive any first or last name

2023-05-23 09:06 UTC, tahirNight requested changes
small changes to do

2023-05-23 09:06 UTC, tahirNight commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-header-members/props.ts
> +    thirdColTitle: string;
rename props to specific attribute

2023-05-23 09:06 UTC, tahirNight commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-members/index.tsx
> +    if (members) members.data.push({ role: 'Developer' });
what is this ?

2023-05-23 09:06 UTC, tahirNight commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-members/index.tsx
> +                                avatarPicture=''
make avatartPicture optional

2023-05-23 09:06 UTC, tahirNight commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-row-members/index.tsx
> +            ></HStack>
what's the purpose of this HStack ? It has 0 children

2023-05-23 09:06 UTC, tahirNight commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-row-members/props.ts
> +    email?: string;
email should be required

2023-05-23 09:21 UTC, youssef-night commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-header-members/props.ts
> +    thirdColTitle: string;
Remove it because it's always the same title

2023-05-23 09:22 UTC, youssef-night commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-members/index.tsx
> +    if (members) members.data.push({ role: 'Developer' });
A little test that i forgot to remove

2023-05-23 09:43 UTC, youssef-night commented on libs/ui/components/contents/organisation-settings/components/members-setting-section/components/table-row-members/index.tsx
> +            ></HStack>
it's was to keep a good space between the two col but it's not realy necessary I remove it

2023-05-23 10:14 UTC, tahirNight approved these changes

2023-05-23 10:28 UTC, merged