Feat/infinite query param for terms
nightborn-be/localise-frontend pull request #34
Opened 2023-05-08 13:19 UTC by youssef-night

2023-05-09 09:41 UTC, youssef-night commented
Like Tahir say I changed my infinite scroll

2023-05-10 08:05 UTC, ThomasNight commented on libs/ui/components/contents/project/glossary/index.tsx
> +                                    }
Create a function in logic and explain it, but I'm not sure this is the best way to do it.
You cannot get the scroll value of the parent and check if scroll value > 80% (or else) -> then load page ?

2023-05-23 09:20 UTC, tahirNight requested changes
small changes to do

2023-05-23 09:20 UTC, tahirNight commented on libs/ui/components/contents/project/glossary/components/table-row-term/props.ts
> +    ref?: React.LegacyRef<HTMLDivElement> | undefined
type of ref is not correct. check this https://stackoverflow.com/questions/66963289/useref-typescript-not-assignable-to-type-legacyrefhtmldivelement

2023-05-23 09:20 UTC, tahirNight commented on libs/ui/components/contents/project/glossary/index.tsx
>              !!newRowTerm.length ? (
avoid using ternary operation, try to do it another way

2023-05-23 09:20 UTC, tahirNight commented on libs/ui/components/contents/project/glossary/logic.ts
>          };
why do have this ? add comments

2023-05-23 09:20 UTC, tahirNight commented on libs/ui/pages/dashboard/projects/[id]/logic.ts
> +    const TermsFetchSize = 25;
put this kind of attribute outside your component, and best practice is to put in all CAPS

2023-05-23 09:20 UTC, tahirNight commented on libs/utils/scroll-percentage/index.ts
> +    const [scrollPercentage, setScrollPercentage] = useState(NaN);
why did u init to NaN and not 0

2023-05-23 09:20 UTC, tahirNight commented on libs/utils/scroll-percentage/index.ts
> +    }, [scrollPercentage]);
explain what this code does

2023-05-23 09:48 UTC, youssef-night commented on libs/ui/components/contents/project/glossary/components/table-row-term/props.ts
> +    ref?: React.LegacyRef<HTMLDivElement> | undefined
I remove it, because it's never used

2023-05-23 10:02 UTC, youssef-night commented on libs/ui/components/contents/project/glossary/index.tsx
>              !!newRowTerm.length ? (
I use a render function

2023-05-23 10:25 UTC, youssef-night commented on libs/utils/scroll-percentage/index.ts
> +    const [scrollPercentage, setScrollPercentage] = useState(NaN);
by default the scroll is not mandatory to begin at 0, in the code we determine the real scroll starting by using the node linked to the ref

2023-05-23 12:47 UTC, tahirNight approved these changes

2023-05-23 12:48 UTC, merged