Input Text Select component
nightborn-be/localise-frontend pull request #6
Opened 2023-03-02 11:08 UTC by youssef-night

2023-03-06 09:10 UTC, ThomasGnightborn requested changes
Some little changes and question but otherwise seems to be good

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-select/index.tsx
> +            {/* INPUT LABEL SECTION */}
No need this to be in capslock

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-select/index.tsx
> +            {/* INPUT SELECT SECTION */}
No need this to be in capslock

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-text-select/index.tsx
> +                onMouseLeave={() => setIsHovered(false)}
It's always better to extract this into a function even if it's for only one instruction (better code readability because you can name the function to explain what this does)

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-text-select/index.tsx
> +                {/* INPUT FIELD SECTION */}
No need this to be in capslock

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-text-select/index.tsx
> +                {/* SELECT SECTION */}
No need this to be in capslock

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-text-select/index.tsx
> +                {/* BUTTON RIGHT SECTION */}
No need this to be in capslock

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-text-select/index.tsx
> +                            }
Better to extract this into a function with if for cases

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-text-select/index.tsx
> +                        menuRightOption='-44px'
When you "hard code" value like this did you test on smaller screens ? (You can do it easily by  reducing the size of your screen with the Developer console)

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-textarea-field/index.tsx
> +                                    : ''
Is the type good ? That's mean that the return of the onKeyDown is a string ? If it's not the case it's better to put undefined or null

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-textarea-field/index.tsx
> +                        top='93px'
These values will always be the same ? if it's not the case it's better to put it in parent's props

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input/index.tsx
>      const textProps = { lineHeight: font?.lineHeight, margin: 0 };
Does the margin will always be at 0 ? If not better to put in in parent's props

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input/index.tsx
> +                {/* INPUT LABEL SECTION */}
No need to be in capslock

2023-03-06 09:10 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input/index.tsx
> +                {/* INPUT FIELD SECTION */}
No need to be in capslock

2023-03-07 10:45 UTC, youssef-night commented on libs/ui/components/inputs/input-label/index.tsx
> +            )}
yes, I want to place font and color in props for futurs changement but Tahir say me no don't think about futur, if we need some changement some body can do it is not a problem

2023-03-07 10:54 UTC, youssef-night commented on libs/ui/components/inputs/input-textarea-field/index.tsx
> +                        top='93px'
yes, I have one component text area and it's unique

2023-03-07 10:58 UTC, youssef-night commented on libs/ui/components/inputs/input-text-select/index.tsx
> +                        menuRightOption='-44px'
No, I don't check how it's render on a small screen in futur I try to do it

2023-03-08 15:26 UTC, ThomasGnightborn approved these changes
Just a last thing to check but it's good ! Well done !

2023-03-08 15:26 UTC, ThomasGnightborn commented on libs/ui/components/inputs/input-text-select/index.tsx
>                              aria-label=''
It's needed to leave it empty ? If not you can remove this props

2023-03-09 11:53 UTC, merged