Input text key component
nightborn-be/localise-frontend pull request #7
Opened 2023-03-03 09:25 UTC by youssef-night

2023-03-08 16:34 UTC, youssef-night commented
https://app.clickup.com/t/861mdmqc2

2023-03-08 16:38 UTC, ThomasNight requested changes

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/contents/icon/icons/copy-clipboard.tsx
> +export const CopyClipBoardLarge = (props: React.SVGProps<SVGSVGElement>) => (
one file for each icon

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/contents/icon/icons/copy-clipboard.tsx
> +        viewBox={props?.viewBox ?? '0 0 28 28'}
we never change the view box

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/contents/icon/icons/copy-clipboard.tsx
> +                fill={'#8F95B2'}
```suggestion
                fill={props.fill ?? '#8F95B2'}
```

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/contents/icon/icons/index.tsx
> +    copyLarge: CopyClipBoardLarge,
keep same names

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/contents/icon/icons/projectLine.tsx
> +            stroke='#E7E9F4'
```suggestion
            stroke={props.stroke ?? '#E7E9F4'}
```

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/index.stories.tsx
> +    displayIcon: (isHovered) => (
```suggestion
    displayIcon: () => (
```

don't take unused params

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/index.stories.tsx
> +    displayIcon: (isHovered) => (
Remove it everywhere

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/index.tsx
> +            onMouseOver={updateHoverState}
setIsHover = true

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/index.tsx
> +            onMouseLeave={updateHoverState}
setIsHover = false

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/inputs/input-project-key/index.tsx
> +                            Projet key
trad

2023-03-08 16:38 UTC, ThomasNight commented on libs/ui/components/inputs/input-project-key/index.tsx
> +                <Box mb='20px' ml='20px'>
rem everywhere

2023-03-09 17:31 UTC, ThomasNight commented on libs/ui/components/contents/icon/icons/index.tsx
> +    copyLarge: CopyClipBoardLarge,
todo: 
```ts
copyClipBoard: CopyClipBoard,
copyClipBoardLarge: CopyClipBoardLarge,
```

2023-03-09 17:32 UTC, ThomasNight commented on libs/ui/components/inputs/button-icon/index.stories.tsx
> +    displayIcon: (isHovered) => (
todo

2023-03-09 17:34 UTC, ThomasNight approved these changes

2023-03-09 17:34 UTC, ThomasNight commented on libs/ui/components/inputs/input-project-key/index.stories.tsx
> +    h: '40x',
fix height

2023-03-09 17:34 UTC, ThomasNight commented
fix conflicts

2023-03-13 11:05 UTC, ThomasNight approved these changes

2023-03-13 11:06 UTC, merged