Searchbar component
nightborn-be/localise-frontend pull request #8
Opened 2023-03-07 10:40 UTC by youssef-night

2023-03-08 16:35 UTC, youssef-night commented
https://app.clickup.com/t/861mcccvc

2023-03-13 07:49 UTC, ThomasNight commented
fix conflicts

2023-03-14 07:47 UTC, ThomasNight requested changes

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +    }, [boxRef]);
useHook instead, search on google react click outside hook

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +export default function SearchIcon({
```suggestion
const SearchInput = <T extends object>({...}) {...}

export default SearchInput
```
Where T is a generic type for forms

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +    leftIcon = <Icon name='search' />,
Icon will never change

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +    marginLeft = '150px',
remove it, use spacing instead

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +    w,
are set by the component
you can do kind/shape/size if you want

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +    placeholder = 'Type to search...',
Don't set a default value for that, need to be translated in every page

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +    placeholderColor = COLORS.InputText.value,
same kind/shape/size

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +    inputBorderRadius = '0px',
kind/shape/size

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +                        <Input
add props to get and change value of input

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/searchbar-tag/index.tsx
> +export default function SearchbarTag({
Not a generic component, only used in a specific context
You should name `SearchTargetLanguages` component and move it to content folder

The tags props should not be JSX.Element but LanguageDTO[]
And you should create tags with the languageDTO[] in the component

The ui will never change, don't pass every params in the props (when implementing the page, we will see what params are needed)

Same for the searchBar, you can only pass the input value and the input function to change the value

And you should use translations for the title and the description

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/searchbar-tag/index.tsx
> +                        <HStack mt='12px'> {tagList.map((obj) => obj)}</HStack>
Pour info c'est exactement la même chose que de faire ça ;)
```suggestion
                        <HStack mt='12px'> {tagList}</HStack>
```

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/searchbar-tag/index.tsx
> +                    {tagList.length !== 0 && (
```suggestion
                    {!tagList.length && (
```

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/searchbar/index.tsx
> +            <InputGroup
clean well done

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/searchbar/index.tsx
> +export default function Searchbar({
I prefer using one component with kind/shape/size instead of having multiple components

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/searchbar/props.ts
> +export type Options = {
What is this used for ?

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/tag/index.tsx
> +export default function Tag({
Same kind/shape/size

2023-03-14 07:47 UTC, ThomasNight commented on libs/ui/components/inputs/tag/index.tsx
> +    onClick,
onDelete

2023-03-14 16:41 UTC, youssef-night commented on libs/ui/components/inputs/button-icon/index.tsx
> +            onMouseOver={updateHoverState}
already fix in another branch

2023-03-15 09:10 UTC, youssef-night commented on libs/ui/components/inputs/button-icon/index.tsx
>              minWidth={'28px'}
already fix in another branch

2023-03-15 09:13 UTC, youssef-night commented on libs/ui/components/inputs/searchbar/props.ts
> +export type Options = {
no utility forgot to remove it

2023-03-15 09:15 UTC, youssef-night commented on libs/ui/components/inputs/button-icon/index.tsx
> +    displayIcon,
already done in another branch

2023-03-15 09:23 UTC, youssef-night commented on libs/ui/components/inputs/search-icon/index.tsx
> +    }, [boxRef]);
I create my own file hooks.tsx and I put the method doing this

2023-03-15 09:31 UTC, youssef-night commented on libs/ui/components/inputs/search-icon/index.tsx
> +    marginLeft = '150px',
cannot use spacing because, it's a specific search bar that have a animation, the animation push at the left the content so I need to have some space at my left

2023-03-15 09:34 UTC, youssef-night commented on libs/ui/components/inputs/search-icon/index.tsx
> +    w,
I will implement kind/shape/size after I merged into the main because I do a lot of refractor in another code and some branch use some code from another branch, I don't want to destroy all of this you think it's a good idea or need to this right now

2023-03-15 10:39 UTC, youssef-night commented on libs/ui/components/inputs/searchbar-tag/index.tsx
> +export default function SearchbarTag({
for the moment I make my own DTO using interface the content of this is for the moment only value I don't know if it's good

2023-03-15 10:40 UTC, youssef-night commented on libs/ui/components/inputs/searchbar-tag/index.tsx
> +                        <HStack mt='12px'> {tagList.map((obj) => obj)}</HStack>
for that tagList.length && display me 0 if nothing is present

2023-03-15 17:30 UTC, ThomasNight commented on libs/ui/components/contents/icon/icons/search.tsx
> +    >
Tu peux faire ça pour les prochains composants, pas besoin de tout changer

2023-03-15 17:33 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +    const searchBarProps: SearchbarProps = {
Mets le direct dans le render, pas besoin de constante pour ça

2023-03-15 17:33 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +                gap={'12px'}
use spacing instead, not all navigators can handle gap, like internet explorer I think ^^

2023-03-15 17:34 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +    const [tagList, setTagList] = useState<Array<LanguageDTO>>(tags);
You don't need a state for that

2023-03-15 17:34 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +    //Attributes
```suggestion
    // Attributes
```
^^

2023-03-15 17:35 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +    //Render
```suggestion
    
    // Render
```
^^

2023-03-15 17:35 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +                    {tagList.length !== 0 && (
```suggestion
                    {!!tags?.length && (
```

2023-03-15 17:36 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +                        <HStack mt='12px' spacing={'4px'}>
Try to avoid margin, to add spaces between two elements
Use Stacks for it

2023-03-15 17:36 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +                            {tagList.map((obj, i) => (
```suggestion
                            {tagList.map((tag, index) => (
```
Be more specific on your variable names

2023-03-15 17:37 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/index.tsx
> +                                    value={obj.value}
don't forget the ```key={`tag-${index}`}```

2023-03-15 17:38 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/props.ts
> +    tags?: Array<LanguageDTO>
```suggestion
    tags?: T[]
 ```

2023-03-15 17:42 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/props.ts
> +    title?: string,
Ptit tuto:
La différence entre
1. `title: string`
2. `title?: string`
3. `title: string | undefined`

Quand tu utilises le composant
`<Composant title={"blabla"} />`
1. le title est obligatoire, il faut le mettre dans tous les cas, sinon typescript casse la tête
2. le title n'est pas obligatoire, tu n'est pas obliger de le mettre et donc est undefined par défaut
3. le title est obligatoire, tu es obligé de le mettre mais il peut être undefined et donc tu dois spécifié title={undefined}

La 3ème option est souvent utilisé pour les calls api, parce que les données ne sont pas récupérées instantanément, ça veut dire que dans les premiers render, la valeur peut être undefined, mais tu dois quand même spécifié la donnée dans le props car ton composant "ne peut pas vivre" sans ce props

2023-03-15 17:50 UTC, ThomasNight commented on libs/ui/components/contents/searchTargetLanguages/types.tsx
> +export interface LanguageDTO {
remove it

2023-03-15 17:52 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/hooks.tsx
> +export default function useOnClickOutside(ref, handler) {
Yup that's it

2023-03-15 17:52 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/hooks.tsx
> +export default function useOnClickOutside(ref, handler) {
You can move to utils/hooks

2023-03-15 17:53 UTC, ThomasNight commented on libs/ui/components/inputs/search-icon/index.tsx
> +    marginLeft = '150px',
weird, we will see later

2023-03-20 08:03 UTC, ThomasNight requested changes

2023-03-21 08:09 UTC, ThomasNight requested changes

2023-03-21 08:09 UTC, ThomasNight commented on libs/ui/components/contents/role/index.tsx
> +    function colorChoice() {
getColor

2023-03-21 08:09 UTC, ThomasNight commented on libs/ui/components/contents/role/index.tsx
> +    // Function
Functions

2023-03-21 08:09 UTC, ThomasNight commented on libs/ui/components/contents/role/index.tsx
> +    function backgroundChoice() {
getBackground

2023-03-21 08:09 UTC, ThomasNight commented on libs/ui/components/contents/role/index.tsx
> +                        { value: 'Admin', label: 'Admin' },
value: Role.ADMIN, label: t(tKeys.common.roles.ADMIN)

Same for the others
Le value, il faut utiliser l'enum et le label il faut utiliser les traductions (demande a quelqu'un du bureau comment faire)

2023-03-22 13:41 UTC, youssef-night commented on libs/ui/components/contents/role/index.tsx
> +            case 'Admin':
I think I don't have this one

2023-03-22 13:41 UTC, youssef-night commented on libs/ui/components/contents/role/props.ts
> +    selectedValue: string,
I think I don't have this one

2023-03-24 10:10 UTC, merged